# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zm7y9usu8iayimbnszkO895wJe4w0o4v

QUESTION 1:Write a program to print the datatypes of the following data

A):- 5
"""

a=5
print(type(a))

"""B):- 2.0

"""

b=2.0
print(type(b))

"""C):- 1+2j"""

c=1+2j
print(type(c))

"""D):- "Biochemistry""""

d="Biochemistry"
print(type(d))

"""QUESTION 2 :  Write a program to reverse a string using for loop S1="Engineering College""""

S1="Engieering College"
S2=""
for i in S1:
  S2=i+S2
print(S2)

"""QUESTION 3: Write a program that reads a string and returns a table of the letters of the alphabet in alphabetical order which occur in the string together with the number of times each letter occurs. Case should be ignored. """

a = input("Enter the String : ")
a = a.lower()
dic={}
alphabet = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
for i in alphabet:
  dic[i] = a.count(i,0,100)
  if dic[i] == 0 :
    del dic[i]

for j in dic:
  print(j,dic[j])

"""QUESTION 4: Create a dictionary to keep track of your friend’s birthdays. Create a dictionary with names and birthdays of friend’s. If user enters the name of the friend then it should return the birthday of the person."""

print("Welcome to the dictionary!!!\n\nI will help you track the birthday of your friend!!! \n\nFollowing are the names of your friends mentioned in the dictionary")
dict  = {"amrit raj" : "12/02/2002" , "shubhankar suman" : "26/07/2000" , "ankit singh" : "01/01/1999" , "puja kumari" : "13/08/1999" , "kaushal verma" : "17/08/2000"} 

names = list(dict.keys())
print(names)
get_input = input("Whose birthday you want to see?\n ")
get_input = get_input.lower()
for i in dict:
  if (get_input==i):
    print("Birthday of", get_input , "is on" , dict[get_input])

"""QUESTION 5 : Create a list consisting of 12 integers and take input from the user. Now create a list to remove all the duplicate elements and display the new list."""



list1 = [1,2,3,4,5,6,7,8,9,10,11,12]
list2 = int(input("Enter the integer"))
list1.append(list2)
list3 = set(list1)
print(list3)

"""QUESTION 6:  Given a two Python lists. Iterate both lists simultaneously such that list1 should display item in original order and list2 in reverse order."""

list1 = ["a","b","c"]
list2 = [1,2,3]
list2.reverse
for i in range(0,3):
  print(list1[i] , list2[i])

"""QUESTION 7 :  Create a tuple of integers. Write a program to count the number of elements
in the tuple. Now, check whether the number (length of tuple) is present in the
tuple, and if present, list the index.
"""

tuple1 = (1,4,6,8,4,9)
length = len(tuple1)
print("The length of tuple of integers is ", length)
if length in tuple1:
  print("The index of tuple is ", tuple1.index(length))